### ISSUE TITLE
Intentar optimizar instalación de dependencias de Dockerfile

### ISSUE THREAD

**Issue by mcarmona99** [mcarmona99/CineTickets#51]
En el Dockerfile, para instalar `poetry` y `pypyr`, previamente hacemos:

```
# Instalación de deps del gestor de tareas y deps; y creación del usuario
RUN apk add \
    gcc \
    libc-dev \
    libffi-dev  \
    && addgroup -S cinetickets  \
    && adduser -S cinetickets -G cinetickets  # usuario y grupo, respectivamente
```

Tenemos que buscar una alternativa a instalar las deps `gcc`, `libc-dev` y `libffi-dev`. Si evitamos instalar estas dependencias, tendremos una construcción que resultará en una imagen más pequeña.

Referente al PMV https://github.com/mcarmona99/CineTickets/milestone/7, ya que está relacionado con la infraestructura de despliegue de la aplicación.

**Comment by mcarmona99** [comment]
Empecemos con [Poetry](https://python-poetry.org/docs/).

Actualmente, instalamos Poetry con pip, con lo que bajamos la dependencia de el repo de Python PyPi.
Como alternativa, tal y como podemos encontrar en la [documentación de Poetry,](https://python-poetry.org/docs/#installation) podemos usar un script escrito en Python para hacer esta instalación. El script se encuentra en https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py. 

En lugar de este script, probaremos con https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py. Ambos son válidos, pero este último es más actual y será usado en futuras versiones.

`get-poetry` además, da errores con respecto a `gcc` aún teniéndolo instalado. Por esto, y por lo anteriormente mencionado referente a actualizaciones, pruebo con `install-poetry`.

Tras hacer pruebas con install-poetry.py (la descarga del archivo la hacemos con wget, que es una dependencia ya incluida en Alpine), veo que funciona con las actuales dependencias (gcc, libc-dev y libffi-dev), pero la construcción no es válida cuando intento quitar al menos una de ellas:

```
...    
raise PoetryInstallationError(
__main__.PoetryInstallationError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install-poetry.py", line 900, in <module>
    sys.exit(main())
  File "install-poetry.py", line 879, in main
    _, path = tempfile.mkstemp(
  File "/usr/local/lib/python3.8/tempfile.py", line 331, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/poetry-installer-error-misqhb2w.log'

```

Descarto entonces la instalación de `Poetry` por script ya que es inevitable instalar las tres dependencias mencionadas.
Aún con esto, cabe la posibilidad de instalar por script en lugar de usando `pip` (`PyPi`). 

A priori, esta no es una buena alternativa ya que instalar mediante script aumenta considerablemente el tiempo de construcción de la imagen. Aún así, instalar por script **es la mejor opción** o mejor dicho, **la recomendada** por sus desarrolladores, ya que al instalar con otros métodos (`pip` o `pipx`) hacemos que Poetry siempre use la versión de Python para la que fue instalado a la hora de crear nuevos entornos virtuales.

No tiene mucho sentido plantearnos ahora instalar `pypyr` por script, ya que, las dependencias `gcc`, `libc-dev` y `libffi-dev` son instaladas siempre ya que son dependencias de `Poetry`. Aún así, investigo si esta instalación es posible. Según su [documentación](https://github.com/pypyr/pypyr) oficial, no parece que existan scripts oficiales de instalación, con lo que se hará usando `pip`.

**Con el uso del script para instalar poetry, el tamaño de la imagen construida es de 239MB.**
